nelmio_api_doc:
    documentation:
        info:
            title: Elfsight Home Task
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    models:
        names:
            - { alias: Comment, type: App\Book\Application\DTO\CommentDTO }
            - { alias: Episode, type: App\Book\Application\DTO\EpisodeDTO }
            - { alias: Error, type: App\Book\Infrastructure\Model\ErrorResponse }
